# Generated by Django 5.0 on 2024-12-09 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table=None,
        ),
    ]
